### ISSUE TITLE
Options disabled

### ISSUE THREAD

**Issue by tin2tin** [technisculpt/blender-text-to-speech-gtts#3]
Great to see you're taking a shot at this. I wanted to do this myself for a long time. 

Since it is placed in Testing, and that is disabled as the default setting, it made it harder to find. 

When running it most of the buttons are disabled:
![image](https://user-images.githubusercontent.com/1322593/155966932-0ea7d7d3-691e-46f8-bdc1-377a0142faea.png)

The add-on seems to install without errors, however, I'm not sure the external modules are installed at all. There isn't any info about that in the console. 

If you want to align the UI with the Blender UI standards, then use Title Case on buttons and no colons. 

```
        layout.use_property_split = True
        layout.use_property_decorate = False
```

Let me know if you need some help with something.

**Comment by technisculpt** [comment]
thanks for the heads up, will change the buttons now. for now you can ungrey the buttons by restoring factory settings. I will change test to dev because there are some things that may be an issue,  wasn't expecting ppl to find this repo until i advertised it somewhere! Will change to test soon, I want to make data persistent between blend sessions then I will remove the hardcoded file paths

**Comment by tin2tin** [comment]
I played around with your add-on. It's amazing how fast it can convert a text to speech. (I needed to set up the paths etc. first. Text export didn't work for me though) 

I also tried some stuff with the ui:
![image](https://user-images.githubusercontent.com/1322593/157012928-77c9c36d-2106-4854-a125-b3a850d5410a.png)

If you like it, the code is here:
```
class TextToSpeech_PT(bpy.types.Panel):
    bl_space_type = 'SEQUENCE_EDITOR'
    bl_region_type = 'UI'
    bl_label = 'Text to Speech'
    bl_category = 'Text to Speech'
    bl_idname = 'SEQUENCER_PT_textToSpeech'

    def draw(self, context):
        layout = self.layout
        layout.use_property_split = True
        layout.use_property_decorate = False

        col = layout.column(align=True)
        col.use_property_split = True
        col.prop(context.scene.text_to_speech, 'accent_enumerator', text='Accent')
        # col.prop(context.scene.text_to_speech, 'pitch', text="Pitch")

        box = layout.box()
        col = box.column(align=True)
        col.use_property_split = False
        col.prop(context.scene.text_to_speech, 'string_field', text = '')
        col.operator('text_to_speech.speak', text = 'Add Speech', icon='ADD')

        col = layout.column()
        col.use_property_split = True
        col.operator('text_to_speech.load', text = 'Import Subtitles as Speech', icon='FILE_FOLDER')

        col = layout.column()
        col.use_property_split = False
        row = col.row(align=True)
        row = row.split(factor=0.80, align=True)
        row.operator('text_to_speech.export', text = 'Export Subtitles', icon='FILE_TICK')
        row.prop(context.scene.text_to_speech, 'mode_enumerator')
```

The export properly should have a File Browser pop-up with an option to select filetype/extension. 

Converting text strips to speech sound strips would be a great feature to add.

**Comment by technisculpt** [comment]
I also want the file browser pop up on export but i couldn't easily implement it like with the import, so i put the export options for now, also ties in with deciding if there should be a field for scratch folder or I might just use the existing bpy.context.scene.render.filepath 

i hopefully implemented persistence across sessions today but I still need to test everything in win10 and linux, then i will look into export options again (not sure if this is in the realm of the blender python API) - then i will remove hardcoded filepaths and maybe merge some / all of this UI, i like the icons 👍 

"Converting text strips to speech sound strips would be a great feature to add." - can you elaborate on this?

**Comment by technisculpt** [comment]
the export might not have worked due to more hardcoded filepaths. i'll improve that stuff shortly and let you know

**Comment by tin2tin** [comment]
This is just super cool:
![text2speech](https://user-images.githubusercontent.com/1322593/157035777-609a125e-da71-4d5b-974a-0abe41be006d.gif)

Text strip to speech would be useful for ex. making a tutorial, where you write the comments in text strips, and then using text2speech to convert all of it to speech. Then you can export the text strips from the View menu as srt subtitles, and export the video with the speech, and then upload to YT, both the video with speech and the srt file as subtitle. 

Also, I coded this Screenwriter/Screenplayer add-on which (also) auto-generates dialog text strips(script to screen in one click), and with text2speech(with the mentioned feature), these could quickly be converted to spoken dialogue: https://github.com/tin2tin/Blender_Screenwriter

**Comment by technisculpt** [comment]
oh i see what you mean,  i should have googled text strips. Not a bad idea 👍

**Comment by tin2tin** [comment]
When you got the paths sorted, maybe I can help you with the text strip to speech sound strip stuff.

**Comment by tin2tin** [comment]
If you need a place for the temp files, the location of the installed add-on doesn't need write permissions on Windows. You can get it this way:
```
import os
path_to_script_dir = os.path.dirname(os.path.abspath(__file__))
```

**Comment by technisculpt** [comment]
i replaced the abs paths with from . import module so you can install via regular .zip method now, just change the name to Text to Speech.zip

**Comment by technisculpt** [comment]
import os
path_to_script_dir = os.path.dirname(os.path.abspath(__file__))

is this so we don't need to open blender as admin for gtts install?

**Comment by technisculpt** [comment]
got the better export implemented let me know if you have any issues
